// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rpgrxiehhgvgpixsvsmc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJwZ3J4aWVoaGd2Z3BpeHN2c21jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzMzU2NTAsImV4cCI6MjA2MDkxMTY1MH0.Y4KC6u1fqlBIrUI4-OLgveSbtv3v6Ngh4N7zWIJC0TY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);